import type { RunReport } from "./report.js";
import type { CheckResult } from "./types.js";

const C: Record<string, { bg: string; fg: string; label: string }> = {
  pass: { bg: "#e7f0e4", fg: "#2e5d24", label: "PASS" },
  warn: { bg: "#fdeee4", fg: "#a04312", label: "WARN" },
  fail: { bg: "#fbe5e8", fg: "#a01c30", label: "FAIL" },
  info: { bg: "#e9eef6", fg: "#2b4a76", label: "INFO" },
  skip: { bg: "#eeeeee", fg: "#666666", label: "SKIP" },
};

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function chip(status: string): string {
  const c = C[status] ?? C.info;
  return `<span class="chip" style="background:${c.bg};color:${c.fg}">${c.label}</span>`;
}

const BASE_CSS = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #f6f4ee; color: #1c1c1a; font: 15px/1.5 -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; }
  .wrap { max-width: 980px; margin: 0 auto; padding: 40px 28px 80px; }
  h1 { font-size: 26px; margin: 0 0 4px; letter-spacing: -0.01em; }
  h2 { font-size: 15px; margin: 34px 0 10px; text-transform: uppercase; letter-spacing: 0.09em; color: #6b6350; }
  .meta { color: #6b6350; font-size: 13.5px; margin-bottom: 6px; }
  .totals { display: flex; gap: 10px; flex-wrap: wrap; margin: 18px 0 6px; }
  .tile { background: #fff; border: 1px solid #e3ddcd; border-radius: 10px; padding: 12px 18px; min-width: 86px; }
  .tile b { display: block; font-size: 24px; }
  .tile span { font-size: 12px; text-transform: uppercase; letter-spacing: 0.06em; color: #6b6350; }
  .chip { display: inline-block; font-size: 11px; font-weight: 700; letter-spacing: 0.05em; padding: 3px 9px; border-radius: 99px; }
  .card { background: #fff; border: 1px solid #e3ddcd; border-radius: 12px; padding: 4px 0; }
  .row { display: grid; grid-template-columns: 70px minmax(0,1fr); gap: 14px; padding: 13px 18px; border-top: 1px solid #efeadd; align-items: start; }
  .row:first-child { border-top: none; }
  .row .t { font-weight: 650; }
  .row .d { color: #4b4638; font-size: 13.5px; margin-top: 2px; }
  details { margin-top: 6px; }
  summary { cursor: pointer; font-size: 12px; color: #8a7f66; }
  pre { background: #f4f1e8; border-radius: 8px; padding: 10px 12px; font-size: 12px; overflow-x: auto; margin: 8px 0 0; }
  .refs { font-size: 12px; color: #8a7f66; margin-top: 4px; }
  table { border-collapse: separate; border-spacing: 0; width: 100%; background: #fff; border: 1px solid #e3ddcd; border-radius: 12px; overflow: hidden; }
  th, td { padding: 11px 14px; text-align: left; font-size: 13.5px; border-top: 1px solid #efeadd; }
  thead th { border-top: none; background: #1c2b4d; color: #f2ede1; font-size: 12px; text-transform: uppercase; letter-spacing: 0.07em; }
  td.first, th.first { font-weight: 650; }
  .foot { margin-top: 34px; color: #8a7f66; font-size: 12.5px; }
`;

export function renderRunHtml(report: RunReport): string {
  const flat = report.packs.flatMap((p) => p.results);
  const count = (s: string) => flat.filter((r) => r.status === s).length;
  const tiles = ["pass", "warn", "fail", "info", "skip"]
    .map(
      (s) =>
        `<div class="tile" style="border-top:3px solid ${C[s].fg}"><b>${count(s)}</b><span>${s}</span></div>`,
    )
    .join("");
  const packs = report.packs
    .map(
      (p) => `
    <h2>${esc(p.name)}</h2>
    <div class="card">${p.results
      .map(
        (r: CheckResult) => `
      <div class="row">
        <div>${chip(r.status)}</div>
        <div>
          <div class="t">${esc(r.title)}</div>
          <div class="d">${esc(r.details)}</div>
          ${r.references?.length ? `<div class="refs">Refs: ${r.references.map(esc).join(" · ")}</div>` : ""}
          ${
            r.evidence
              ? `<details><summary>evidence</summary><pre>${esc(JSON.stringify(r.evidence, null, 2))}</pre></details>`
              : ""
          }
        </div>
      </div>`,
      )
      .join("")}</div>`,
    )
    .join("");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>fhir-verify — ${esc(report.serverUrl)}</title><style>${BASE_CSS}</style></head><body><div class="wrap">
  <h1>fhir-verify report</h1>
  <div class="meta">Server: <b>${esc(report.serverUrl)}</b></div>
  <div class="meta">Run: ${esc(report.startedAt)} → ${esc(report.finishedAt)} · ${esc(report.tool)} v${esc(report.version)}</div>
  <div class="totals">${tiles}</div>
  ${packs}
  <div class="foot">Generated by fhir-verify — the operational basics every production FHIR integration depends on. Synthetic data only.</div>
</div></body></html>`;
}

/** Build a cross-server behavior matrix from multiple run reports. */
export function renderMatrixHtml(reports: RunReport[]): string {
  const servers = reports.map((r) => {
    const labeled = (r as RunReport & { label?: string }).label;
    if (labeled) return labeled;
    try {
      const u = new URL(r.serverUrl);
      return u.hostname.replace(/^www\./, "");
    } catch {
      return r.serverUrl;
    }
  });
  // union of check ids in first-seen order
  const ids: string[] = [];
  const titleById = new Map<string, string>();
  for (const rep of reports)
    for (const p of rep.packs)
      for (const c of p.results) {
        if (!titleById.has(c.id)) {
          ids.push(c.id);
          titleById.set(c.id, c.title);
        }
      }
  const cell = (rep: RunReport, id: string) => {
    for (const p of rep.packs) for (const c of p.results) if (c.id === id) return c;
    return undefined;
  };
  const rows = ids
    .map((id) => {
      const tds = reports
        .map((rep) => {
          const c = cell(rep, id);
          return `<td title="${c ? esc(c.details) : "not run"}">${c ? chip(c.status) : "—"}</td>`;
        })
        .join("");
      return `<tr><td class="first">${esc(titleById.get(id) ?? id)}<div class="refs">${esc(id)}</div></td>${tds}</tr>`;
    })
    .join("");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>fhir-verify — behavior matrix</title><style>${BASE_CSS}</style></head><body><div class="wrap">
  <h1>FHIR server behavior matrix</h1>
  <div class="meta">${reports.length} servers · generated by fhir-verify (hover a cell for details)</div>
  <div style="overflow-x:auto;margin-top:16px"><table>
    <thead><tr><th class="first">Check</th>${servers.map((s) => `<th>${esc(s)}</th>`).join("")}</tr></thead>
    <tbody>${rows}</tbody>
  </table></div>
  <div class="foot">Same probes, same synthetic data, one command per server. Certification proves a server can; operations is where it does.</div>
</div></body></html>`;
}
